struct ListUser *initalization();
struct User *addUser(struct sockaddr_in client_addr, char* name);
void deleteUser(int id);
void displayList();
struct ListRoom *initalizationRoom();
struct Room* addRoom(char* name);
void deleteRoom(int id);
void displayListRoom();
void decripteHeader(struct Chat_message messageRecu,struct sockaddr_in client_addr);
void connectServer(struct sockaddr_in client_addr, char* userName);
void sendMessage(struct sockaddr_in client_addr, struct Chat_message messageEnvoye);
void disconnectServer(int idUtilisateur);
struct User* findUser(int id);
void say(struct Chat_message messageRecu);
void join(struct Chat_message messageRecu);
void ackJoin (int idRoom, int idUser,int etat);
void leave(struct Header header);
void alive(struct Header header);
void ack(struct Chat_message messageRecu);
int main(void);
